eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8700
spring:
  application:
    name: service-web
  zipkin:
     base-url: http://localhost:9411
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
feign:
  hystrix:
    enabled: true


#
#   spring.cloud.config.label 指明远程仓库的分支
#
#   spring.cloud.config.profile
#        dev开发环境配置文件
#        test测试环境
#        pro正式环境
#
#    spring.cloud.config.uri= http://localhost:8888/ 指明配置服务中心的网址。

