server:
  port: 8761
spring:
  profiles: peer1
#通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8769/eureka/


