eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    lxcs-admin:
      path: /lxcs-admin/**
      serviceId: service-feign
    lxcs-app:
      path: /lxcs-app/**
      serviceId: service-feign
